### ISSUE TITLE
关于老师您的正则表达式30分钟入门教程

### ISSUE THREAD

**Issue by 959201963** [deerchao/weixin.next#1]
分枝条件里的：不幸的是，刚才那个表达式也能匹配010)12345678或(022-87654321这样的“不正确”的格式。要解决这个问题里面。

\(?0\d{2}\)?[- ]?\d{8}|0\d{2}[- ]?\d{8} 这句是不是也能能匹配到上面的不正确格式？

老师有空的时候解答一下

**Comment by deerchao** [comment]
是的. 为了解决这样的问题, 需要使用  (?(groupname)yes|no) 这样的语法构造(学名 Test Group).
